## NUMPY

In [1]:
import numpy as np

In [2]:
np.__version__

'2.3.5'

In [3]:
import sys
sys.version

'3.13.9 | packaged by Anaconda, Inc. | (main, Oct 21 2025, 19:11:29) [Clang 20.1.8 ]'

## Creating Arrays

In [4]:
my_list = [0,1,2,3,4,5]
my_list

[0, 1, 2, 3, 4, 5]

In [5]:
type(my_list)

list

## Converting list to array

In [6]:
arr = np.array(my_list)

In [7]:
arr

array([0, 1, 2, 3, 4, 5])

In [8]:
type(arr)

numpy.ndarray

In [9]:
type(my_list)

list

In [10]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [11]:
np.arange(0,10,1)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [13]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
np.arange(3.0)

array([0., 1., 2.])

In [15]:
np.arange(9)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [16]:
np.arange(0,5)

array([0, 1, 2, 3, 4])

In [17]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [18]:
np.arange(20,10)  # 1st arg < 2nd arg

array([], dtype=int64)

In [19]:
np.arange(-20,10)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7,   8,   9])

In [20]:
np.arange(-16,10)

array([-16, -15, -14, -13, -12, -11, -10,  -9,  -8,  -7,  -6,  -5,  -4,
        -3,  -2,  -1,   0,   1,   2,   3,   4,   5,   6,   7,   8,   9])

In [21]:
np.arange(-20,-10)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11])

In [23]:
np.arange() # it missed stop argument

TypeError: arange() requires stop to be specified.

In [24]:
np.arange(10,30,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [25]:
np.arange(0,10,3)

array([0, 3, 6, 9])

In [26]:
np.arange(10,30,3,3)  # it understands only 3 arguments

TypeError: Cannot interpret '3' as a data type

In [27]:
np.zeros(3) # parameter tuning

array([0., 0., 0.])

In [28]:
np.zeros(5,dtype = int)   # hyperparameter tuning

array([0, 0, 0, 0, 0])

In [29]:
np.zeros((2,2),dtype = int)

array([[0, 0],
       [0, 0]])

In [30]:
np.zeros((2,10))  # it will 1st arg is row & 2nd arg column

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [31]:
np.zeros((5,10),dtype = int)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [32]:
np.ones(3)

array([1., 1., 1.])

In [33]:
np.ones(3,dtype = int)

array([1, 1, 1])

In [34]:
np.ones((3,3),dtype = int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [35]:
np.ones((5,4) ,dtype = int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [36]:
np.twos(2,3) # twos is not function

AttributeError: module 'numpy' has no attribute 'twos'

In [37]:
rand(3,2)

NameError: name 'rand' is not defined

In [38]:
random.rand(3,2)

NameError: name 'random' is not defined

In [39]:
np.random.rand(5)

array([0.47969129, 0.01016874, 0.05322077, 0.23475476, 0.45416035])

In [40]:
np.rand(4)

AttributeError: module 'numpy' has no attribute 'rand'

In [41]:
np.random.rand(4,3)

array([[0.05510325, 0.67742809, 0.42880492],
       [0.21525902, 0.44957534, 0.66639668],
       [0.65701174, 0.2517849 , 0.21444566],
       [0.12408232, 0.43157212, 0.15120202]])

In [42]:
np.random.randint(2,4)

3

In [43]:
np.random.randint(2,20)

11

In [44]:
np.random.randint(2,20,2)

array([13, 11])

In [45]:
np.random.randint(2,20,5)

array([17,  8,  9,  9, 13])

In [46]:
np.arange(1,13)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [47]:
np.arange(1,13).reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [48]:
np.random.randint(5,9)

8

In [49]:
np.random.randint(10,40,(10,10))

array([[11, 37, 27, 13, 37, 20, 20, 12, 11, 25],
       [15, 24, 34, 23, 16, 16, 36, 33, 14, 20],
       [23, 29, 16, 27, 15, 34, 38, 25, 11, 29],
       [35, 28, 13, 39, 35, 39, 32, 24, 11, 24],
       [12, 23, 20, 11, 18, 29, 38, 33, 18, 11],
       [17, 10, 37, 13, 12, 37, 21, 33, 11, 28],
       [36, 39, 24, 23, 37, 39, 32, 14, 19, 30],
       [23, 22, 19, 18, 26, 31, 28, 18, 12, 33],
       [27, 26, 13, 29, 38, 23, 27, 15, 28, 34],
       [34, 11, 25, 11, 21, 11, 28, 14, 16, 23]])

In [50]:
np.arange(1,13)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [51]:
np.arange(1,13).reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

## Slicing in matrix

In [52]:
b = np.random.randint(10,20,(5,4))
b

array([[10, 15, 18, 11],
       [18, 14, 15, 17],
       [15, 19, 14, 17],
       [17, 19, 17, 19],
       [11, 13, 10, 10]])

In [53]:
type(b)

numpy.ndarray

In [54]:
b

array([[10, 15, 18, 11],
       [18, 14, 15, 17],
       [15, 19, 14, 17],
       [17, 19, 17, 19],
       [11, 13, 10, 10]])

In [55]:
b[:]

array([[10, 15, 18, 11],
       [18, 14, 15, 17],
       [15, 19, 14, 17],
       [17, 19, 17, 19],
       [11, 13, 10, 10]])

In [56]:
b[1:3] # we can get 1st and 2nd row and it will print entire row 

array([[18, 14, 15, 17],
       [15, 19, 14, 17]])

In [57]:
b

array([[10, 15, 18, 11],
       [18, 14, 15, 17],
       [15, 19, 14, 17],
       [17, 19, 17, 19],
       [11, 13, 10, 10]])

In [58]:
b[1,2] # it will print specific 

np.int64(15)

In [59]:
b[1,3]

np.int64(17)

In [60]:
b[1,-1]

np.int64(17)

In [61]:
b[-1,-1]

np.int64(10)

In [62]:
b[2:3]

array([[15, 19, 14, 17]])

In [63]:
b[0,-2]

np.int64(18)

In [64]:
b[0:-2]

array([[10, 15, 18, 11],
       [18, 14, 15, 17],
       [15, 19, 14, 17]])

In [65]:
b[-4:2]

array([[18, 14, 15, 17]])

## Operations

In [66]:
a = np.random.randint(10,20,10)
a

array([12, 12, 16, 17, 17, 17, 12, 18, 17, 12])

In [67]:
id(a)

6008949040

In [68]:
arr

array([0, 1, 2, 3, 4, 5])

In [69]:
arr2 = np.random.randint(0,100,(10,10))

In [70]:
arr2

array([[69, 73,  7,  6, 23, 66, 91, 47, 29, 88],
       [66, 47, 79, 83, 13, 17, 63, 78, 36, 84],
       [68, 60,  1,  2, 99, 93, 69, 44, 78, 15],
       [18, 18, 98, 95, 13, 29, 73, 89, 15, 79],
       [32, 32, 22, 11, 53, 86, 54, 33,  3,  8],
       [68, 12, 94, 60, 42, 87, 29, 85, 99, 69],
       [26, 63,  7, 26, 83, 31, 15, 17, 74, 59],
       [48, 34, 94, 52, 31, 80, 61,  4, 40, 47],
       [74, 29,  0, 54, 97, 99, 50, 92, 66, 95],
       [81, 44, 34, 70, 43, 62, 39, 69, 58,  5]])

In [71]:
arr2[::-1]

array([[81, 44, 34, 70, 43, 62, 39, 69, 58,  5],
       [74, 29,  0, 54, 97, 99, 50, 92, 66, 95],
       [48, 34, 94, 52, 31, 80, 61,  4, 40, 47],
       [26, 63,  7, 26, 83, 31, 15, 17, 74, 59],
       [68, 12, 94, 60, 42, 87, 29, 85, 99, 69],
       [32, 32, 22, 11, 53, 86, 54, 33,  3,  8],
       [18, 18, 98, 95, 13, 29, 73, 89, 15, 79],
       [68, 60,  1,  2, 99, 93, 69, 44, 78, 15],
       [66, 47, 79, 83, 13, 17, 63, 78, 36, 84],
       [69, 73,  7,  6, 23, 66, 91, 47, 29, 88]])

In [72]:
arr2

array([[69, 73,  7,  6, 23, 66, 91, 47, 29, 88],
       [66, 47, 79, 83, 13, 17, 63, 78, 36, 84],
       [68, 60,  1,  2, 99, 93, 69, 44, 78, 15],
       [18, 18, 98, 95, 13, 29, 73, 89, 15, 79],
       [32, 32, 22, 11, 53, 86, 54, 33,  3,  8],
       [68, 12, 94, 60, 42, 87, 29, 85, 99, 69],
       [26, 63,  7, 26, 83, 31, 15, 17, 74, 59],
       [48, 34, 94, 52, 31, 80, 61,  4, 40, 47],
       [74, 29,  0, 54, 97, 99, 50, 92, 66, 95],
       [81, 44, 34, 70, 43, 62, 39, 69, 58,  5]])

In [73]:
arr2[::-2]

array([[81, 44, 34, 70, 43, 62, 39, 69, 58,  5],
       [48, 34, 94, 52, 31, 80, 61,  4, 40, 47],
       [68, 12, 94, 60, 42, 87, 29, 85, 99, 69],
       [18, 18, 98, 95, 13, 29, 73, 89, 15, 79],
       [66, 47, 79, 83, 13, 17, 63, 78, 36, 84]])

In [74]:
arr2[::-3]

array([[81, 44, 34, 70, 43, 62, 39, 69, 58,  5],
       [26, 63,  7, 26, 83, 31, 15, 17, 74, 59],
       [18, 18, 98, 95, 13, 29, 73, 89, 15, 79],
       [69, 73,  7,  6, 23, 66, 91, 47, 29, 88]])

In [75]:
arr2

array([[69, 73,  7,  6, 23, 66, 91, 47, 29, 88],
       [66, 47, 79, 83, 13, 17, 63, 78, 36, 84],
       [68, 60,  1,  2, 99, 93, 69, 44, 78, 15],
       [18, 18, 98, 95, 13, 29, 73, 89, 15, 79],
       [32, 32, 22, 11, 53, 86, 54, 33,  3,  8],
       [68, 12, 94, 60, 42, 87, 29, 85, 99, 69],
       [26, 63,  7, 26, 83, 31, 15, 17, 74, 59],
       [48, 34, 94, 52, 31, 80, 61,  4, 40, 47],
       [74, 29,  0, 54, 97, 99, 50, 92, 66, 95],
       [81, 44, 34, 70, 43, 62, 39, 69, 58,  5]])

In [76]:
arr2[3::]

array([[18, 18, 98, 95, 13, 29, 73, 89, 15, 79],
       [32, 32, 22, 11, 53, 86, 54, 33,  3,  8],
       [68, 12, 94, 60, 42, 87, 29, 85, 99, 69],
       [26, 63,  7, 26, 83, 31, 15, 17, 74, 59],
       [48, 34, 94, 52, 31, 80, 61,  4, 40, 47],
       [74, 29,  0, 54, 97, 99, 50, 92, 66, 95],
       [81, 44, 34, 70, 43, 62, 39, 69, 58,  5]])

In [77]:
arr.max()

np.int64(5)

In [78]:
arr.min()

np.int64(0)

In [79]:
arr.mean()

np.float64(2.5)

In [80]:
arr.median()

AttributeError: 'numpy.ndarray' object has no attribute 'median'

In [81]:
from numpy import *

In [82]:
arr.median()

AttributeError: 'numpy.ndarray' object has no attribute 'median'

## Indexing

In [83]:
mat = np.arange(0,100).reshape(10,10)

In [84]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [85]:
row = 4
col = 5

In [86]:
col

5

In [87]:
row

4

In [88]:
mat[row,col]

np.int64(45)

In [89]:
mat[:]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [90]:
mat[6]

array([60, 61, 62, 63, 64, 65, 66, 67, 68, 69])

In [91]:
mat[:,col]

array([ 5, 15, 25, 35, 45, 55, 65, 75, 85, 95])

In [92]:
mat[2:6,2:4] # first part is row and 2nd part is column

array([[22, 23],
       [32, 33],
       [42, 43],
       [52, 53]])

In [93]:
mat[1:2,2:4]

array([[12, 13]])

## Masking

In [94]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [95]:
mat[mat < 50] # fliter

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [96]:
mat[mat > 60]

array([61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77,
       78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94,
       95, 96, 97, 98, 99])

In [97]:
mat[mat != 50]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])