In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3])

In [3]:
print("Array a:", a)

Array a: [1 2 3]


In [4]:
b = np.array([1,2,3,4,4,4,4])
print("Array b :",b)

Array b : [1 2 3 4 4 4 4]


In [5]:
c = np.linspace(0,1,5)
print("Array c :",c)

Array c : [0.   0.25 0.5  0.75 1.  ]


In [6]:
d = np.zeros((2,3))
print("Array d :\n",d)

Array d :
 [[0. 0. 0.]
 [0. 0. 0.]]


In [7]:
e = np.ones((2,4))
print("Array e :\n",e)

Array e :
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [8]:
f = np.eye(4)
print("Array f :\n",f)

Array f :
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


## Array Manipulation Functions

In [9]:
a1 = np.array([1,2,3])
reshaped = np.reshape(a1,(1,3))
print("Reshaped array :\n",reshaped)
    

Reshaped array :
 [[1 2 3]]


In [10]:
f1 = np.array([[1,2],[3,4]])
flattend = np.ravel(f1)
print("Flattend Array :",flattend)

Flattend Array : [1 2 3 4]


In [11]:
e1 = np.array([[1, 2], [3, 4]])
transposed = np.transpose(e1)
print("Transposed Array :",e1)

Transposed Array : [[1 2]
 [3 4]]


In [12]:
a2 = np.array([1, 2])
b2 = np.array([3, 4])
stacked = np.vstack([a2,b2])
print("stacked Array :",stacked)

stacked Array : [[1 2]
 [3 4]]


## Mathematical Functions

In [13]:
g = np.array([1, 2, 3, 4])
added = np.add(g, 2)  # Add 2 to each element
print("Added 2 to g:", added)

Added 2 to g: [3 4 5 6]


In [14]:
# Square each element
squared = np.power(g, 2)  # Square each element
print("Squared g:", squared)

Squared g: [ 1  4  9 16]


In [15]:
 #Square root of each element
sqrt_val = np.sqrt(g)  # Square root of each element
print("Square root of g:", sqrt_val)

Square root of g: [1.         1.41421356 1.73205081 2.        ]


In [16]:
print(a1)
print(g)

[1 2 3]
[1 2 3 4]


## Statistical Functions

In [17]:
s = np.array([1, 2, 3, 4])
mean = np.mean(s)
print("Mean of s:", mean)

Mean of s: 2.5


In [18]:
# Standard deviation of an array
std_dev = np.std(s)
print("Standard deviation of s:", std_dev)

Standard deviation of s: 1.118033988749895


In [19]:
#Minimum element of an array
minimum = np.min(s)
print("min of s:",minimum)

min of s: 1


In [20]:
# Maximum element of an array
maximum = np.max(s)
print("Max of s:", maximum)

Max of s: 4


## Linear Algebra Functions

In [21]:
# Create a matrix
matrix = np.array([[1, 2], [3, 4]])

In [22]:
inverse = np.linalg.inv(matrix)
print("Inverse of matrix:\n", inverse)

Inverse of matrix:
 [[-2.   1. ]
 [ 1.5 -0.5]]


## Random Sampling Functions

In [23]:
# Generate random values between 0 and 1
random_vals = np.random.rand(3)  # Array of 3 random values between 0 and 1
print("Random values:", random_vals)

Random values: [0.81921778 0.99792508 0.20446621]


In [24]:
# Set seed for reproducibility
np.random.seed(0)

# Generate random values between 0 and 1
random_vals = np.random.rand(3)  # Array of 3 random values between 0 and 1
print("Random values:", random_vals)

Random values: [0.5488135  0.71518937 0.60276338]


In [25]:
rand_ints = np.random.randint(0, 10, size=5)  # Random integers between 0 and 10
print("Random integers:", rand_ints)

Random integers: [3 7 9 3 5]


In [26]:
# Set seed for reproducibility
np.random.seed(0)

# Generate random integers
rand_ints = np.random.randint(0, 10, size=5)  # Random integers between 0 and 10
print("Random integers:", rand_ints)

Random integers: [5 0 3 3 7]


## Boolean & Logical Functions

In [27]:
# Check if all elements are True
# all
logical_test = np.array([True, False, True])
all_true = np.all(logical_test)  # Check if all are True
print("All elements True:", all_true)

All elements True: False


In [28]:
# Check if all elements are True
logical_test = np.array([True, False, True])
all_true = np.all(logical_test)  # Check if all are True
print("All elements True:", all_true)

All elements True: False


In [29]:
# Check if any elements are True
# any
any_true = np.any(logical_test)  # Check if any are True
print("Any elements True:", any_true)

Any elements True: True


## Set Operations

In [30]:
# Intersection of two arrays
set_a = np.array([1, 2, 3, 4])
set_b = np.array([3, 4, 5, 6])
intersection = np.intersect1d(set_a, set_b)
print("Intersection of a and b:", intersection)

Intersection of a and b: [3 4]


In [31]:
# Union of two arrays
union = np.union1d(set_a, set_b)
print("Union of a and b:", union)

Union of a and b: [1 2 3 4 5 6]


## Array Attribute Functions

In [32]:
# Array attributes
a = np.array([1, 2, 3])
shape = a.shape  # Shape of the array
size = a.size    # Number of elements
dimensions = a.ndim  # Number of dimensions
dtype = a.dtype   # Data type of the array

print("Shape of a:", shape)
print("Size of a:", size)
print("Number of dimensions of a:", dimensions)
print("Data type of a:", dtype)

Shape of a: (3,)
Size of a: 3
Number of dimensions of a: 1
Data type of a: int64


In [35]:
x = np.array([10,20,2.5])
x

array([10. , 20. ,  2.5])

In [36]:
x.astype(int)

array([10, 20,  2])

In [38]:
z1 = np.arange(12).reshape(3,4)
z2 = np.arange(12,24).reshape(3,4)
z1
z2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [39]:
z1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [40]:
z2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

## scalar operations

In [42]:
z1 + 2

array([[ 2,  3,  4,  5],
       [ 6,  7,  8,  9],
       [10, 11, 12, 13]])

In [43]:
z1 - 2

array([[-2, -1,  0,  1],
       [ 2,  3,  4,  5],
       [ 6,  7,  8,  9]])

In [44]:
z2 * 2

array([[24, 26, 28, 30],
       [32, 34, 36, 38],
       [40, 42, 44, 46]])

In [45]:
z1 ** 2

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [46]:
z1 % 2

array([[0, 1, 0, 1],
       [0, 1, 0, 1],
       [0, 1, 0, 1]])

In [47]:
z1 // 2

array([[0, 0, 1, 1],
       [2, 2, 3, 3],
       [4, 4, 5, 5]])

In [48]:
z1 / 2

array([[0. , 0.5, 1. , 1.5],
       [2. , 2.5, 3. , 3.5],
       [4. , 4.5, 5. , 5.5]])

## relational Operators

In [49]:
z1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [52]:
z1 < 2 # here we get bool

array([[ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [54]:
z1[z1 < 2] # flitering

array([0, 1])

In [55]:
z2 > 20

array([[False, False, False, False],
       [False, False, False, False],
       [False,  True,  True,  True]])

In [56]:
z2[z2>20]

array([21, 22, 23])

## Vector Operation

In [57]:
z1 

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [58]:
z2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [59]:
z1 + z2

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [60]:
z1 - z2

array([[-12, -12, -12, -12],
       [-12, -12, -12, -12],
       [-12, -12, -12, -12]])

In [61]:
z2 - z1

array([[12, 12, 12, 12],
       [12, 12, 12, 12],
       [12, 12, 12, 12]])

In [62]:
z1 * z2

array([[  0,  13,  28,  45],
       [ 64,  85, 108, 133],
       [160, 189, 220, 253]])

In [63]:
z1 / z2


array([[0.        , 0.07692308, 0.14285714, 0.2       ],
       [0.25      , 0.29411765, 0.33333333, 0.36842105],
       [0.4       , 0.42857143, 0.45454545, 0.47826087]])

In [64]:
z1 // z2

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [65]:
z1 != z2

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

## Array Functions

In [68]:
k1 = np.random.random((3,3))
k1 = np.round(k1*100)
k1

array([[93.,  7.,  9.],
       [ 2., 83., 78.],
       [87., 98., 80.]])

In [69]:
np.max

<function max at 0x119691470>

In [70]:
k1.max()

np.float64(98.0)

In [71]:
k1.min

<function ndarray.min>

In [72]:
np.sum(k1)

np.float64(537.0)

In [73]:
np.prod(k1)

np.float64(51744179410560.0)

## Statistics related fuctions

In [74]:
k1

array([[93.,  7.,  9.],
       [ 2., 83., 78.],
       [87., 98., 80.]])

In [75]:
k1.mean()

np.float64(59.666666666666664)

In [76]:
np.mean(k1)

np.float64(59.666666666666664)

In [77]:
np.median(k1)

np.float64(80.0)

In [78]:
np.std(k1)

np.float64(38.42452920263883)

## Trignometry Functions

In [79]:
k1

array([[93.,  7.,  9.],
       [ 2., 83., 78.],
       [87., 98., 80.]])

In [80]:
np.sin(k1)

array([[-0.94828214,  0.6569866 ,  0.41211849],
       [ 0.90929743,  0.96836446,  0.51397846],
       [-0.82181784, -0.57338187, -0.99388865]])

In [81]:
np.cos(k1)

array([[ 0.3174287 ,  0.75390225, -0.91113026],
       [-0.41614684,  0.24954012, -0.85780309],
       [ 0.56975033, -0.81928825, -0.11038724]])

In [82]:
np.tan(k1)

array([[-2.98738626,  0.87144798, -0.45231566],
       [-2.18503986,  3.88059631, -0.59918   ],
       [-1.44241747,  0.69985365,  9.00365495]])

In [84]:
np.cosh(k1)

array([[1.22562277e+40, 5.48317035e+02, 4.05154203e+03],
       [3.76219569e+00, 5.56431877e+35, 3.74920850e+33],
       [3.03801511e+37, 1.81898547e+42, 2.77031119e+34]])

## Iterating

In [85]:
p1 = np.arange(0,10)
p1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [86]:
for i in p1 :
    print(i)

0
1
2
3
4
5
6
7
8
9


In [87]:
for i in enumerate(p1):
    print(i)

(0, np.int64(0))
(1, np.int64(1))
(2, np.int64(2))
(3, np.int64(3))
(4, np.int64(4))
(5, np.int64(5))
(6, np.int64(6))
(7, np.int64(7))
(8, np.int64(8))
(9, np.int64(9))


In [88]:
p2 = np.arange(0,12).reshape(3,4)
p2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [89]:
for i in p2:
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [90]:
for i in enumerate(p2):
    print(i)

(0, array([0, 1, 2, 3]))
(1, array([4, 5, 6, 7]))
(2, array([ 8,  9, 10, 11]))


In [91]:
for i in np.nditer(p2):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11


In [92]:
for i in enumerate(np.nditer(p2)):
    print(i)

(0, array(0))
(1, array(1))
(2, array(2))
(3, array(3))
(4, array(4))
(5, array(5))
(6, array(6))
(7, array(7))
(8, array(8))
(9, array(9))
(10, array(10))
(11, array(11))


## Reshaping

In [93]:
p2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [94]:
np.transpose(p2)

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [96]:
p2.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])